spring: 
  profiles:
    active:
    - dev
---
server:
  port: 2001
  servlet:
    context-path: /

spring:
  profiles: dev
  application:
    name: microservice-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_film?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

eureka:
  instance:
    hostname: localhost
    appname: microservice-provider
    instance-id: microservice-provider:2001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://localhost:1001/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5

info:
  groupId: $project.groupId$
  artifactId: $project.artifactId$
  version:  $project.version$
  description: $project.description$
  encoding: $project.build.sourceEncoding$
  java:
    version: $java.version$
---
server:
  port: 2001
  servlet:
    context-path: /

spring:
  profiles: test
  application:
    name: microservice-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_film?serverTimezone=UTC
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    cache: false

eureka:
  instance:
    hostname: localhost
    appname: microservice-provider
    instance-id: microservice-provider:2001
    prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://localhost:1001/eureka
    healthcheck:
      enabled: true
    lease:
      duration: 5

info:
  groupId: $project.groupId$
  artifactId: $project.artifactId$
  version:  $project.version$
  description: $project.description$
  encoding: $project.build.sourceEncoding$
  java:
    version: $java.version$








